server:
  port: 8000

spring:
  application:
    name: cloud-consumer-openFgrign
  profiles:
    active: dev # 表示开发环境
  cloud:
    nacos:
      discovery:
        server-addr:  ${spring.cloud.nacos.config.server-addr} #配置Nacos地址
      config:
        server-addr: localhost:8848 #配置Nacos地址
        file-extension: yaml
        group: ${spring.application.name}
        namespace: b83990dd-7552-4d28-8ee4-e2440cf19bc9
management:
  endpoints:
    web:
      exposure:
        include: '*'


